apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-blue
# these are deployment labels
  labels:
    purpose: blue-green
    project: safety
    color: blue
spec:
  replicas: 4
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: blue-green
      project: safety
      color: blue
    # pod definition
  template: 
    metadata:
      labels:
        purpose: blue-green
        project: safety
        color: blue
    spec:
      containers:
      - name: nginx
        image: nginx